"""add vault items

Revision ID: 2bf24b7a9778
Revises: 148ef2e81f98
Create Date: 2026-01-28 14:55:13.112186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '2bf24b7a9778'
down_revision: Union[str, Sequence[str], None] = '148ef2e81f98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluator_states_id'), table_name='evaluator_states')
    op.drop_table('evaluator_states')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluator_states',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('focus', sa.VARCHAR(), nullable=False),
    sa.Column('consistency_score', sa.INTEGER(), nullable=False),
    sa.Column('missed_reminders', sa.INTEGER(), nullable=True),
    sa.Column('pending_tasks', sqlite.JSON(), nullable=True),
    sa.Column('ai_summary', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_evaluator_states_id'), 'evaluator_states', ['id'], unique=False)
    # ### end Alembic commands ###
