"""add gym domain tables

Revision ID: c975da53c94a
Revises: 
Create Date: 2025-12-15 16:58:31.940890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c975da53c94a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gym_amenities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gym_id', sa.Integer(), nullable=False),
    sa.Column('sauna', sa.Boolean(), nullable=True),
    sa.Column('steam', sa.Boolean(), nullable=True),
    sa.Column('ice_bath', sa.Boolean(), nullable=True),
    sa.Column('recovery_room', sa.Boolean(), nullable=True),
    sa.Column('pool', sa.Boolean(), nullable=True),
    sa.Column('parking', sa.Boolean(), nullable=True),
    sa.Column('showers', sa.Boolean(), nullable=True),
    sa.Column('locker', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gym_id')
    )
    op.create_index(op.f('ix_gym_amenities_id'), 'gym_amenities', ['id'], unique=False)
    op.create_table('gym_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gym_id', sa.Integer(), nullable=False),
    sa.Column('equipment_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gym_equipment_id'), 'gym_equipment', ['id'], unique=False)
    op.create_table('gym_pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gym_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('duration', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gym_pricing_id'), 'gym_pricing', ['id'], unique=False)
    op.create_table('gym_trainers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gym_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('certifications', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gym_trainers_id'), 'gym_trainers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gym_trainers_id'), table_name='gym_trainers')
    op.drop_table('gym_trainers')
    op.drop_index(op.f('ix_gym_pricing_id'), table_name='gym_pricing')
    op.drop_table('gym_pricing')
    op.drop_index(op.f('ix_gym_equipment_id'), table_name='gym_equipment')
    op.drop_table('gym_equipment')
    op.drop_index(op.f('ix_gym_amenities_id'), table_name='gym_amenities')
    op.drop_table('gym_amenities')
    # ### end Alembic commands ###
