"""initial tables

Revision ID: 3120a67b7f7a
Revises: 
Create Date: 2025-11-27 22:41:57.454099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3120a67b7f7a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gym',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('locality', sa.String(), nullable=True),
    sa.Column('monthly_price', sa.Float(), nullable=True),
    sa.Column('yearly_price', sa.Float(), nullable=True),
    sa.Column('daily_pass_price', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('gallery_images', sa.JSON(), nullable=True),
    sa.Column('membership_options', sa.JSON(), nullable=True),
    sa.Column('equipment_list', sa.JSON(), nullable=True),
    sa.Column('classes_available', sa.JSON(), nullable=True),
    sa.Column('personal_training_available', sa.Boolean(), nullable=True),
    sa.Column('is_popular', sa.Boolean(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('cover_image', sa.String(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('opening_hours', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gym_id'), 'gym', ['id'], unique=False)
    op.create_table('gym_daily_analytics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('gym_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('leads', sa.Integer(), nullable=True),
    sa.Column('premium_views', sa.Integer(), nullable=True),
    sa.Column('engagement_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gym_id'], ['gym.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gym_daily_analytics_id'), 'gym_daily_analytics', ['id'], unique=False)
    op.create_table('gym_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('gym_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gym_id'], ['gym.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gym_events_id'), 'gym_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gym_events_id'), table_name='gym_events')
    op.drop_table('gym_events')
    op.drop_index(op.f('ix_gym_daily_analytics_id'), table_name='gym_daily_analytics')
    op.drop_table('gym_daily_analytics')
    op.drop_index(op.f('ix_gym_id'), table_name='gym')
    op.drop_table('gym')
    # ### end Alembic commands ###
