import Card from "../../components/ui/Card";
import Button from "../../components/ui/Button";

export default function Coach() {
  return (
    <div className="px-4 py-6 max-w-3xl mx-auto">
      <div className="flex items-center gap-4 mb-4">
        <div className="w-14 h-14 rounded-full bg-gradient-to-r from-sky-500 to-violet-500 shadow-lg" />
        <div>
          <h2 className="text-lg font-bold">FitAI Coach</h2>
          <p className="text-slate-400">Your AI fitness companion</p>
        </div>
      </div>

      <Card className="mb-4">
        <p className="text-slate-300 mb-3">How can I help today?</p>
        <div className="flex gap-2">
          <Button>Generate Workout</Button>
          <Button className="bg-neutral-700">Meal Plan</Button>
        </div>
      </Card>

      <Card>
        <h3 className="font-semibold mb-2">Recent session summary</h3>
        <p className="text-slate-400">Summary generated by AI about your last 7 days.</p>
      </Card>
    </div>
  );
}
